defmodule BotArmyOutreach.Workers.SyncReportGenerator do
  @moduledoc "Generates daily outreach analytics reports and syncs to Google Drive"
  require Logger

  alias BotArmyOutreach.Stores.ContactStore

  @doc "Generate SYNC_REPORT.md with outreach metrics and wrong turns"
  def generate_report do
    try do
      stalled = ContactStore.stalled_contacts(7)
      recent_replies = ContactStore.recent_replies()
      stats = ContactStore.conversion_stats()
      missed_follow_ups = get_missed_follow_ups()

      report = build_report(stalled, recent_replies, stats, missed_follow_ups)

      case sync_to_google_drive(report) do
        :ok ->
          Logger.info("SYNC_REPORT.md generated and synced")
          {:ok, report}

        {:error, reason} ->
          Logger.error("Failed to sync report to Google Drive: #{inspect(reason)}")
          {:error, reason}
      end
    rescue
      e ->
        Logger.error("Error generating sync report: #{inspect(e)}")
        {:error, e}
    end
  end

  defp build_report(stalled, recent_replies, stats, missed_follow_ups) do
    today = Date.utc_today() |> Date.to_iso8601()

    """
    # Outreach Sync Report — #{today}

    ## Summary

    **Total Contacts:** #{stats.total}
    **Open:** #{stats.open}
    **Deals:** #{stats.deals}
    **Rejected:** #{stats.rejected}
    **Conversion Rate:** #{stats.conversion_rate}%

    ---

    ## 🚨 Wrong Turns (Attention Needed)

    ### Stalled Contacts (No update > 7 days)
    #{format_stalled(stalled)}

    ### Missed Follow-ups
    #{format_missed_follow_ups(missed_follow_ups)}

    ---

    ## ✅ Recent Activity

    ### New Replies (Last 7 days)
    #{format_recent_replies(recent_replies)}

    ---

    ## 📊 Analytics

    ### Response Rate
    - Total contacted: #{stats.total}
    - With replies: #{Enum.count(recent_replies)}
    - Response rate: #{calc_response_rate(stats, recent_replies)}%

    ### Average Days to Reply
    - Days to first reply: #{avg_reply_time(recent_replies)}

    ### Conversion Funnel
    - Cold: #{count_by_stage(stalled ++ recent_replies, "cold")}
    - Follow-up scheduled: #{count_by_stage(stalled ++ recent_replies, "follow_up_scheduled")}
    - Replied: #{count_by_stage(stalled ++ recent_replies, "replied")}
    - Conversation: #{count_by_stage(stalled ++ recent_replies, "conversation")}
    - Deal: #{stats.deals}

    ---

    *Generated by Bot Army Outreach Bot*
    """
  end

  defp format_stalled([]), do: "None — all contacts are fresh ✓"

  defp format_stalled(contacts) do
    Enum.map_join(contacts, "\n", fn c ->
      "- **#{c.name}** (#{c.company}): last contact #{days_ago(c.last_contact)} days ago"
    end)
  end

  defp format_missed_follow_ups([]), do: "None — all follow-ups on schedule ✓"

  defp format_missed_follow_ups(contacts) do
    Enum.map_join(contacts, "\n", fn c ->
      "- **#{c.name}**: scheduled for #{days_ago(c.next_follow_up)} days ago"
    end)
  end

  defp format_recent_replies([]), do: "None yet"

  defp format_recent_replies(contacts) do
    Enum.map_join(contacts, "\n", fn c ->
      "- **#{c.name}** (#{c.company}): #{c.notes || "no notes"}"
    end)
  end

  defp get_missed_follow_ups do
    ContactStore.list_contacts(needs_follow_up: true)
  end

  defp days_ago(nil), do: "never"

  defp days_ago(datetime) do
    now = DateTime.utc_now()
    diff = DateTime.diff(now, datetime, :second)
    div(diff, 86400)
  end

  defp calc_response_rate(stats, recent_replies) do
    if stats.total > 0,
      do: Float.round(Enum.count(recent_replies) / stats.total * 100, 2),
      else: 0.0
  end

  defp avg_reply_time(contacts) do
    if Enum.empty?(contacts) do
      0
    else
      total_days =
        Enum.reduce(contacts, 0, fn c, acc ->
          case c.first_contact_date do
            nil -> acc
            date -> acc + days_ago(date)
          end
        end)

      Float.round(total_days / Enum.count(contacts), 2)
    end
  end

  defp count_by_stage(contacts, stage) do
    Enum.count(contacts, fn c -> c.stage == stage end)
  end

  defp sync_to_google_drive(report) do
    case get_para_root() do
      {:ok, para_root} ->
        path =
          Path.join([
            para_root,
            "Projects",
            "Claude-Code-Sessions",
            "outreach-report-#{Date.utc_today() |> Date.to_iso8601()}.md"
          ])

        File.write(path, report)

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp get_para_root do
    case Gnat.request(:gnat, "para.system.config", "{}", receive_timeout: 3000) do
      {:ok, reply} ->
        case Jason.decode(reply.body) do
          {:ok, %{"data" => %{"root_directory" => root}}} ->
            {:ok, root}

          _ ->
            {:error, "Invalid PARA config response"}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end
end
